theme: minima
title: Mark Himsley
description: A collection of notes and thoughts
logo: https://avatars.githubusercontent.com/u/1175979
header_pages: [''] # see https://github.com/jekyll/minima/issues/219
minima: # see https://github.com/jekyll/minima
  date_format: "%Y-%m-%d" # see http://shopify.github.io/liquid/filters/date/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
plugins:
  - jekyll-optional-front-matter