namespace: default
resources:
  - hello-app.yaml
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: hello-app-web
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`hello.lxiv.uk`) && PathPrefix(`/`)
      - op: replace
        path: /spec/routes/0/services/0/namespace
        value: default
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: hello-app-websecure
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`hello.lxiv.uk`) && PathPrefix(`/`)
      - op: replace
        path: /spec/routes/0/services/0/namespace
        value: default
      - op: replace
        path: /spec/tls/secretName
        value: wildcard-lan-lxiv-uk-tls-secret
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: hello-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: hello.lxiv.uk
      - op: replace
        path: /spec/tls/0/hosts/0
        value: hello.lxiv.uk
      - op: replace
        path: /spec/tls/0/secretName
        value: wildcard-lan-lxiv-uk-tls-secret